### ISSUE TITLE
Booleans com erro

### ISSUE THREAD

**Issue by dukemagus** [cogitas3d/OrtogOnBlender#14]
Traceback (most recent call last):
  File "c:\OrtogOnBlender\Blender280\2.80\scripts\addons\OrtogOnBlender-master\BooleanaOsteo.py", line 473, in execute
    BooleanaOsteoGeralDef(self, context)
  File "c:\OrtogOnBlender\Blender280\2.80\scripts\addons\OrtogOnBlender-master\BooleanaOsteo.py", line 380, in BooleanaOsteoGeralDef
    bpy.data.collections['Collection'].objects.unlink(obj)
KeyError: 'bpy_prop_collection[key]: key "Collection" not found'

location: <unknown location>:-1

**Comment by cogitas3d** [comment]
Hi @dukemagus !

The models have to be in collection "Collection".
