### ISSUE TITLE
Photogrammetry

### ISSUE THREAD

**Issue by juangmagic** [cogitas3d/OrtogOnBlender#18]
Hello everyone. 
I have some experience using blender for dental models and I just found ortogon. I think this is a wonderful project and I want to thank you for such a great effort in developing open-source software. Most of the functions are running well. However, I´m getting an error with the start photogrammetry option.

I tried all the available algorithms, but only smvs+meshlab kind of work, but without texture. When I use OpenMVG + Open MVS, I obtain the next message 

Pairs that have valid intrinsic and high support of points are displayed:
 Choose one pair manually by typing the two integer indexes

No matter which pair I select, I always end up obtaining the next error:

**5. Colorize Structure

The input SfM_Data file "C:\Users\JFran\AppData\Local\Temp\tmpgsn49vdm/OpenMVG\reconstruction_sequential/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "C:\Users\AppData\Local\Temp\tmpgsn49vdm/OpenMVG\reconstruction_sequential/sfm_data.bin" cannot be read.

The input SfM_Data file "C:\Users\AppData\Local\Temp\tmpgsn49vdm/OpenMVG\reconstruction_sequential/robust.bin" cannot be read.

The input SfM_Data file "C:\Users\AppData\Local\Temp\tmpgsn49vdm/OpenMVG/reconstruction_sequential/sfm_data.bin" cannot be read.
(  0.0000 sec |   0.0000 sec) Importing OBJ 'C:\\Users\\AppData\\Local\\Temp\\tmpgsn49vdm/MVS/scene_dense_mesh_texture.obj'...
Progress:   0.00%**

After that, I'm getting this a few times.

**FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AppData\\Local\\Temp\\tmpgsn49vdm/MVS/scene_dense_mesh_texture.obj'**

I couldn't find a solution online, so I reinstalled ortogon just in case. However, I still have the same issue. Something similar occurs when I use meshroom algorithm. I´m very sorry if this is a simple thing, but I´m quite new at programming.

Thanks in advance 
JG

**Comment by mkvisions** [comment]
Hello there, 
I have got allmost similar problem with photogrammetry in OOB. But first of all I want to say thanks for rhis project. Dear profesor CM it looks fantastic.  But, I have got problem with running it on:
Windows 10 64b,
Blender 2.82a installed
With/without Ubuntu for Windows runnig,
With Windows MVS libraries installed,
16 Gb RAM,
 Intel core i7,
Nvidia RTX 2070 Max-Q design.


I installed OrtogOnBlender simillary to this manual:

_http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/Instalacao_Windows.html_

When I started a Ortog as an Administrator (it is taked out from Eset virus detecting) i get this at console:

**Read prefs: C:\OrtogOnBlender\Blender280\2.80\config\userpref.blend
found bundled python: C:\OrtogOnBlender\Blender280\2.80\python
Warning: class IMPORT_MESH_OT_off contains a properties which should be an annotation!
**C:\OrtogOnBlender\Blender280\2.80\scripts\addons\import_off.py:180
    make annotation: IMPORT_MESH_OT_off.filter_glob
    make annotation: IMPORT_MESH_OT_off.axis_forward
    make annotation: IMPORT_MESH_OT_off.axis_up
Warning: class EXPORT_MESH_OT_off contains a prope**rties which should be an annotation!
C:\OrtogOnBlender\Blender280\2.80\scripts\addons\import_off.py:180
    make annotation: EXPORT_MESH_OT_off.filter_glob
    make annotation: EXPORT_MESH_OT_off.axis_forward
    make annotation: EXPORT_MESH_OT_off.axis_up
    make annotation: EXPORT_MESH_OT_off.use_colors
register_class(...):
Warning: 'measureit_main_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'measureit_conf_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'measureit_render_panel' doesn't contain '_PT_' with prefix & suffix
Falta algum ponto anat├┤mico (ANB)!
Falta algum ponto anat├┤mico (ANB)!
Warning: class ORTOG_UI_Local contains a properties which should be an annotation!
C:\OrtogOnBlender\Blender280\2.80\scripts\addons\OrtogOnBlender-master\__init__.py:3041
    make annotation: ORTOG_UI_Local.path
    make annotation: ORTOG_UI_Local.path_slices_img
    make annotation: ORTOG_UI_Local.path_photo
    make annotation: ORTOG_UI_Local.filepathmha
    make annotation: ORTOG_UI_Local.filepathcsv
    make annotation: ORTOG_UI_Local.filepathobj
    make annotation: ORTOG_UI_Local.filepathvideo**

When I to started photogrammetry proces (OpenMVG+OpenMVS), it fails in the moment when it importing mesh from MVS:

**Traceback (most recent call last):
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\__init__.py", line 145, in execute
    return import_obj.load(context, **keywords)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\import_obj.py", line 933, in load
    float_func = get_float_func(filepath)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\import_obj.py", line 840, in get_float_func
    file = open(filepath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MARTIN~1\\AppData\\Local\\Temp\\tmpfev5s91w/MVS/scene_dense_mesh_texture.obj'

location: C:\OrtogOnBlender\Blender280\2.80\scripts\modules\bpy\ops.py:200

location: C:\OrtogOnBlender\Blender280\2.80\scripts\modules\bpy\ops.py:200
Error: Traceback (most recent call last):
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\__init__.py", line 145, in execute
    return import_obj.load(context, **keywords)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\import_obj.py", line 933, in load
    float_func = get_float_func(filepath)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\import_obj.py", line 840, in get_float_func
    file = open(filepath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MARTIN~1\\AppData\\Local\\Temp\\tmpfev5s91w/MVS/scene_dense_mesh_texture.obj'

location: C:\OrtogOnBlender\Blender280\2.80\scripts\modules\bpy\ops.py:200

Traceback (most recent call last):
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\OrtogOnBlender-master\FotogrametriaOpenMVG.py", line 465, in execute
    GeraModeloFotoDef(self, context)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\OrtogOnBlender-master\FotogrametriaOpenMVG.py", line 388, in GeraModeloFotoDef
    bpy.ops.import_scene.obj(filepath=tmpOBJface, filter_glob="*.obj;*.mtl")
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\__init__.py", line 145, in execute
    return import_obj.load(context, **keywords)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\import_obj.py", line 933, in load
    float_func = get_float_func(filepath)
  File "C:\OrtogOnBlender\Blender280\2.80\scripts\addons\io_scene_obj\import_obj.py", line 840, in get_float_func
    file = open(filepath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MARTIN~1\\AppData\\Local\\Temp\\tmpfev5s91w/MVS/scene_dense_mesh_texture.obj'

location: C:\OrtogOnBlender\Blender280\2.80\scripts\modules\bpy\ops.py:200**

Also I have got simylar problem/errors with other tipes of Photogrammetry (only AliceVision works). So I think the problem is somewhre in implementation of "linux" algorithms into windows (I wanted try a Ubuntu 18.04, but there is a problem with instalation - Intel RST and tunes of Archaeological data on laptop.) Also that is the reason, why blender python scripts dont work corectly. In my opinion... 

Can you give me some tipes to get some results?
We use other 3D tools like Blender, MarvelousDesigner, UE4, SP, Agisoft, RC and so on frequently for past two years, but your tool looks as a guy, that we missed alot.... We want to learn our students this program, becaouse it is free and if it works, it looks relativelly user friendly. 
Best regards (and sorry for my tired English, I allmost fall a sleep),
Bc. Martin Košťál
3D Atelier
Department of Archaeology and Museology, FA, Masaryk University, Brno, CZ.

**Comment by juangmagic** [comment]
Did you try updating?
With the last version of Orthogonblender, my problem got solved.
The new version also lets you obtain pictures from video and then perform the photogrammetry prosses.

**Comment by mkvisions** [comment]
I download the latest version. Anyway, when I try it, the ortog crash (close itself)

**Comment by issamdakir** [comment]
Juanjmagic, mkvisions i see quite same fault in path try to  go to file code and make double backslashs in the path like this sometimes it solve the problem
C:\\Users\\MARTIN~1\\AppData\\Local\\Temp\\tmpfev5s91w\\MVS\\scene_dense_mesh_texture.obj
